import {money,monthNow,monthLabel,shiftMonth} from './core.js';
import {debtStats,cardMonthStats} from './amounts.js';
const esc=v=>String(v??'').replace(/[&<>"']/g,c=>({'&':'&amp;','<':'&lt;','>':'&gt;','"':'&quot;',"'":'&#39;'}[c]));
export function accountSections(debts,payments,charges,month,day=1){
 function group(card){
  const list=debts.filter(d=>(d.account_type==='card')===card),title=card?'Mis tarjetas':'Deudas y abonos';
  return `<section class="panel debt-panel" aria-label="${title}"><div class="panel-heading"><div><h2>${title}</h2><p>${card?'Tu saldo actual y los movimientos del mes seleccionado.':'Tus deudas continúan aquí aunque cambies de mes.'}</p></div><button class="primary" id="${card?'new-card':'new-debt'}">+ Agregar ${card?'tarjeta':'deuda'}</button></div><div class="debt-total"><span>${card?'Total que debes en tarjetas':'Saldo pendiente total'}</span><strong>${money(list.reduce((sum,d)=>sum+debtStats(d,payments,charges).remaining,0))}</strong></div><div class="debt-cards">${list.map(d=>{
   const monthly=cardMonthStats(d.id,payments,charges,month,day),s=debtStats(d,payments,charges),charged=charges.filter(c=>c.debt_id===d.id).reduce((sum,c)=>sum+c.amount,0);
   const history=[...payments.filter(p=>p.debt_id===d.id).map(p=>({...p,date:p.payment_date,type:'payment'})),...charges.filter(c=>c.debt_id===d.id).map(c=>({...c,date:c.charge_date,type:'charge'}))].sort((a,b)=>b.date.localeCompare(a.date)||String(b.created_at||'').localeCompare(String(a.created_at||'')));
   return `<article class="debt-card"><div class="debt-card-top"><div><h3>${esc(d.title)}</h3><span class="badge ${s.remaining?'pending':'paid'}">${s.remaining?'Por pagar':'Al día'}</span></div><button class="text-button" data-debt-edit="${d.id}">Editar ${card?'tarjeta':'deuda'}</button></div>${card?`<div class="card-current"><span>Debes ahora · todos los meses</span><strong>${money(s.remaining)}</strong></div>`:''}<div class="debt-numbers"><div><span>${card?'Saldo inicial':'Total registrado'}</span><strong>${money(d.amount)}</strong></div><div><span>${card?'Compras y cargos':'Has abonado'}</span><strong>${money(card?charged:s.paid)}</strong></div><div><span>${card?'Has abonado':'Falta por pagar'}</span><strong>${money(card?s.paid:s.remaining)}</strong></div></div>${card?`<div class="card-month"><span>${esc(monthLabel(month))}</span><div><span>Compras y cargos <strong>${money(monthly.spent)}</strong></span><span>Abonaste <strong>${money(monthly.paid)}</strong></span></div></div>`:''}<p class="debt-estimate">${s.months===0?'¡Estás al día!':s.months?`Si abonas ${money(d.monthly_payment)} cada mes: unos ${s.months} meses${s.months<=1200?`, hasta ${esc(monthLabel(shiftMonth(monthNow(),s.months)))}`:''}. Sin compras ni intereses nuevos.`:'Puedes abonar un valor diferente cada vez.'}</p>${card?'<p class="helper">El abono de referencia solo estima el plazo. Tú eliges cuánto pagar cada vez.</p>':''}${d.notes?`<p class="debt-note">${esc(d.notes)}</p>`:''}<div class="card-actions">${card?`<button class="primary" data-card-charge="${d.id}">+ Registrar compra</button>`:''}<button class="outline" data-debt-pay="${d.id}" ${s.remaining?'':'disabled'}>${card?'Abonar':' + Registrar abono'}</button></div><details class="debt-history"><summary>${card?'Movimientos':'Historial de abonos'} (${history.length})</summary>${history.map(p=>`<div class="debt-payment"><div><strong>${p.type==='charge'?(p.charge_type==='fee'?'Cargo / interés':'Compra'):'Abono'} · ${money(p.amount)}</strong><span>${esc(p.date.split('-').reverse().join('/'))}${p.description||p.notes?' · '+esc(p.description||p.notes):''}</span></div><button class="text-button" ${p.type==='charge'?'data-charge-edit':'data-payment-edit'}="${p.id}">${p.type==='charge'?'Corregir compra':'Corregir abono'}</button></div>`).join('')||'<p>Todavía no hay movimientos.</p>'}</details></article>`;
  }).join('')||`<div class="empty-state"><strong>${card?'Agrega tu tarjeta':'Empieza con tu primera deuda'}</strong><p>${card?'Registra el saldo que debes hoy; después añade tus compras y abonos.':'Registra cuánto debes y después agrega cada abono.'}</p></div>`}</div><div class="budget-caption">${card?'Cada compra o cargo aumenta lo que debes. Tu dinero libre solo baja cuando registras un abono; así no se descuenta dos veces. No registres nuevamente como compra el saldo inicial.':'Solo los abonos se descuentan del presupuesto del mes de su fecha. El plan mensual no aparta dinero automáticamente.'}</div></section>`;
 }
 return group(true)+group(false);
}
