import {money,totals} from './core.js';
import {flowStats,periodBounds} from './periods.js';
export function flowView(rows,previous,month,day,credit){
 const t=totals(rows),s=flowStats(rows,previous,month,day),b=periodBounds(month,day);
 const status=!t.income?'Faltan ingresos por registrar':s.afterPending<0?'Hay compromisos por cubrir':'Tus compromisos registrados están cubiertos';
 const guidance=!t.income?'Registra lo que recibiste para evaluar el período.':s.afterPending<0?`Faltan ${money(-s.afterPending)} para cubrir pagos y apartados. Revisa los gastos pendientes antes de agregar otros.`:`Después de cubrir los pendientes y apartados quedarían ${money(s.afterPending)}.`;
 const legacy=rows.filter(r=>!r.budget_date&&!r.payment_date).length;
 return `<section class="panel flow-panel" aria-label="Flujo de dinero"><div class="panel-heading"><div><h2>Así va tu dinero</h2><p>Del ${b.start.split('-').reverse().join('/')} al ${b.end.split('-').reverse().join('/')}. Según lo que has registrado.</p></div></div><div class="flow-status ${s.afterPending<0?'flow-alert':''}"><strong>${status}</strong><p>${guidance}</p></div><div class="flow-grid"><article><span>Entró</span><strong>${money(t.income)}</strong></article><article><span>Salió · pagos realizados</span><strong>${money(t.paid)}</strong></article><article><span>Flujo neto de efectivo</span><strong>${money(s.net)}</strong><small>No incluye apartados ni compras a crédito.</small></article><article><span>Después de pendientes y apartados</span><strong>${money(s.afterPending)}</strong></article></div><div class="flow-insights"><p>${s.paidRatio===null?'Sin porcentaje: aún no hay ingresos.':`Has pagado el ${s.paidRatio}% de tus ingresos registrados.`} ${s.overdue?`Hay ${s.overdue} pago(s) vencido(s) sin marcar.`:'No hay vencimientos pendientes anteriores a hoy en este período.'}</p><p>${s.daily===null?'Este período ya terminó.':`Quedan ${s.days} días del período. Si repartes lo restante después de compromisos: ${money(s.daily)} por día.`} Esta referencia no contempla gastos que aún no hayas registrado.</p><p>${s.change===null?'No hay registros del período anterior para comparar.':`Pagos realizados frente al período anterior: ${s.change>0?'+':''}${money(s.change)}. Compara con cautela si alguno de los períodos está incompleto.`}</p><p>Tarjetas en este período: compras y cargos ${money(credit.spent)}, abonos ${money(credit.paid)}. ${credit.spent>credit.paid?`La deuda aumentó ${money(credit.spent-credit.paid)} por estos movimientos.`:credit.paid>credit.spent?`La deuda bajó ${money(credit.paid-credit.spent)} por estos movimientos.`:'Sin aumento neto por estos movimientos.'}</p>${legacy?`<p class="legacy-note">${legacy} registro(s) antiguo(s) sin fecha: conservan su mes original. Abre «Editar» y añade la fecha correcta para ubicarlos en tu corte.</p>`:''}</div></section>`;
}
